version: '3.4'
services:
  db:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: restudemy
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  restudemy:
    image: raphasalomao/restudemy
    restart: always
    build: ./02 RestWithSpringBoot
    working_dir: /02 RestWithSpringBoot
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./02 RestWithSpringBoot:/02 RestWithSpringBoot
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge
